# -*- coding: utf-8 -*-
"""turbidez_lagoa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1et8v5uSg3jeMIkqQpPeQaeWgE5zdBINa

**Objetivo:** Detectar alterações ópticas na água da Lagoa da Conceição associadas ao rompimento da barragem de evapoinfiltração da CASAN.
"""

!pip install xee

import ee
import geemap
import xarray as xr
import xee
from xee import helpers
import shapely.geometry
import matplotlib.pyplot as plt

ee.Authenticate()

ee.Initialize(
    project="ee-marciobcure",
    opt_url="https://earthengine-highvolume.googleapis.com"
)

coords = [
    [-48.466616, -27.609322],
    [-48.466616, -27.582622],
    [-48.433228, -27.582622],
    [-48.433228, -27.609322],
    [-48.466616, -27.609322]
]

shapely_aoi = shapely.geometry.Polygon(coords)

roi = ee.Geometry.Polygon([coords])

def coastal_water_quality(img):

    # Máscara de nuvem
    cloud = img.select('probability')
    cloud_free = cloud.lt(20)

    # Reflectância
    sr = img.select('B.*').multiply(0.0001)

    # Máscara de água
    mndwi = sr.normalizedDifference(['B3', 'B11']).rename('mndwi')
    water = mndwi.gt(0)

    # Banda mais robusta para turbidez
   # turbidity = sr.select('B5').rename('turbidity')

    # NDCI
    ndci = (
        sr.normalizedDifference(['B5', 'B4'])
        .rename('ndci')
    )

    return (
        ndci
        .updateMask(cloud_free)
        .updateMask(water)
        .copyProperties(img, ['system:time_start'])
    )

sen2 = (
    ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
    .linkCollection(
        ee.ImageCollection("COPERNICUS/S2_CLOUD_PROBABILITY"),
        'probability'
    )
    .filterBounds(roi)
    .filterDate("2019-01-01", "2026-05-31")
    .map(coastal_water_quality)
)

#target_crs = 'EPSG:3857'
target_crs = 'EPSG:31982'
#target_crs = 'EPSG:4326'

scale = 30

grid_params = helpers.fit_geometry(
    geometry=shapely_aoi,
    grid_crs=target_crs,
    grid_scale=(scale, -scale)
)

ds = xr.open_dataset(
    sen2,
    engine='ee',
    **grid_params
)

print(ds)

!pip install netcdf4

import netCDF4

ds.to_netcdf('ndci_lagoa.nc')

plt.figure(figsize=(8,8))

ds['ndci'].isel(time=15).plot(
    cmap='inferno',
    vmin=0,
    vmax=0.05
)

plt.title("NDCI")
plt.show()

before = ds.sel(time=slice('2019-01-01', '2021-01-24'))
after = ds.sel(time=slice('2021-01-25', '2026-05-31'))

baseline = before['ndci'].mean(dim='time')
baseline.max()

impact = after['ndci'].mean(dim='time')
impact.min()

anomaly = impact - baseline
anomaly

plt.figure(figsize=(10,8))

baseline.plot(
    cmap='RdBu_r',
    vmin=-0.21,
    vmax=0.21
)

plt.title("Baseline espectral antes do rompimento")
plt.show()

plt.figure(figsize=(10,8))

impact.plot(
    cmap='RdBu_r',
    vmin=-0.21,
    vmax=0.21
)

plt.title("Baseline espectral depois do rompimento")
plt.show()

plt.figure(figsize=(10,8))

anomaly.plot(
    cmap='RdBu_r',
    vmin=-0.01,
    vmax=0.01
)

plt.title("Anomalia espectral pós-rompimento")
plt.show()

"""## Série temporal"""

#import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Mapa 1
baseline.plot(
    ax=axes[0],
    cmap='RdBu_r',
    vmin=-0.21,
    vmax=0.21,
    add_colorbar=False
)
axes[0].set_title("NDCI médio antes do rompimento")

# Mapa 2
impact.plot(
    ax=axes[1],
    cmap='RdBu_r',
    vmin=-0.21,
    vmax=0.21,
    add_colorbar=False
)
axes[1].set_title("NDCI médio depois do rompimento")

# Mapa 3
im = anomaly.plot(
    ax=axes[2],
    cmap='RdBu_r',
    vmin=-0.01,
    vmax=0.01,
    add_colorbar=False
)
axes[2].set_title("NDCI médio pós-rompimento")

# Barra de cores compartilhada para os dois primeiros mapas
sm1 = plt.cm.ScalarMappable(
    cmap='RdBu_r',
    norm=plt.Normalize(vmin=-0.6, vmax=0.8)
)
sm1.set_array([])

cbar1 = fig.colorbar(
    sm1,
    ax=[axes[0], axes[1]],
    fraction=0.046,
    pad=0.04
)
cbar1.set_label("Baseline espectral")

# Barra de cores para o terceiro mapa
sm2 = plt.cm.ScalarMappable(
    cmap='RdBu_r',
    norm=plt.Normalize(vmin=-0.3, vmax=0.2)
)
sm2.set_array([])

cbar2 = fig.colorbar(
    sm2,
    ax=axes[2],
    fraction=0.046,
    pad=0.04
)
cbar2.set_label("Anomalia espectral")

plt.tight_layout()
plt.show()

0.3*0.2

ts = ds['ndci'].mean(dim=['x', 'y'])

plt.figure(figsize=(15,5))

ts.plot()

plt.axvline(
    pd.to_datetime('2021-01-25'),
    color='red',
    linestyle='--'
)

plt.title("Mudança temporal da reflectância")
plt.show()
